config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :qnas do
    resources :qnacomments, only: [:create, :destroy], defaults: { format: 'js' }
  end
  resources :notices
  resources :posts do
    resources :comments, only: [:create, :destroy], defaults: { format: 'js' }
  end
  get '/posts/:membertype/search' => 'posts#search'
  root 'home#temp'
  get 'home/temp'
  get 'home/index'
  get 'home/matching'
  get '/mypages/:user_id' => "mypages#index"
  put '/mypages/:user_id/like', to: 'mypages#upvote', as: 'like_mypage'
  put '/mypages/:user_id/dislike', to: 'mypages#downvote', as: 'dislike_mypage'
  post '/posts/:post_id' =>"comments#create"
  get '/reviews/new/:post_id' => 'reviews#new'
  post '/reviews/:post_id' => 'reviews#create'
  post '/portfolios/create' => "portfolios#create"
  get '/portfolios/index'
  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/mypage/index'
  get 'portfolios/edit' => "portfolios#edit"
  post '/portfolios/update' => "portfolios#update"
  get '/matching/:post_id/:name' => "posts#matching", :constraints  => { :name => /[0-z\.]+/ }
  devise_for :users
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    # if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/matching.rb
class Matching < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/mypage.rb
class Mypage < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :portfolios
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :user
  paginates_per 5 
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :reviews
  has_many :matchings
  scope :published, -> {where.not(created_at: nil)}
  scope :unpublished, -> {where(created_at: nil)}
  paginates_per 3 
  def self.search(query)
    self.where("membertype LIKE ?","%#{query}%")
  end
end

app/models/qna.rb
class Qna < ActiveRecord::Base
  belongs_to :user
  has_many :qnacomments
  paginates_per 5
end

app/models/qnacomment.rb
class Qnacomment < ActiveRecord::Base
  belongs_to :user
  belongs_to :qna
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  paginates_per 3 
end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :assign_default_role
  rolify
  acts_as_voter
  # 프로필 사진 추가를 위해 Uploader 생성
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # validates :name, presence: true, uniqueness: true
  has_many :posts
  has_many :reviews
  has_many :comments
  has_many :qnacomments
  has_many :ratings
  # User Avatar Validation
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  # validate :password_complexity
  
  # def password_complexity
  #   return if password.blank? || password =~ /^(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,15}$/

  #   errors.add :password, '를 숫자, 특수문자를 포함하여 6자 이상으로 설정해주세요.'
  # end

  scope :supply, -> {where(user_type: "1")}
  scope :demand, -> {where(user_type: "2")}
  scope :admin, -> {where(user_type: "3")}

  def assign_default_role
    if self.user_type == "1"
      add_role(:supply)
    elsif self.user_type =="2"
      add_role(:demand)
    else
      add_role(:admin)
    end
  end
  
  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end
end

app/controllers/qnas_controller.rb
class QnasController < ApplicationController
  before_action :set_qna, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  # GET /qnas
  # GET /qnas.json
  def index
    @qnas = Qna.all
    @qnas = Qna.order("created_at DESC").page params[:page]
  end

  # GET /qnas/1
  # GET /qnas/1.json
  def show
    @qnacomment = Qnacomment.new
  end

  # GET /qnas/new
  def new
    @qna = Qna.new
  end

  # GET /qnas/1/edit
  def edit
  end

  # POST /qnas
  # POST /qnas.json
  def create
    @qna = Qna.new(qna_params)
    @qna.user_id = current_user.id
    respond_to do |format|
      if @qna.save
        format.html { redirect_to @qna, notice: 'Qna was successfully created.' }
        format.json { render :show, status: :created, location: @qna }
      else
        format.html { render :new }
        format.json { render json: @qna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qnas/1
  # PATCH/PUT /qnas/1.json
  def update
    respond_to do |format|
      if @qna.update(qna_params)
        format.html { redirect_to @qna, notice: 'Qna was successfully updated.' }
        format.json { render :show, status: :ok, location: @qna }
      else
        format.html { render :edit }
        format.json { render json: @qna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qnas/1
  # DELETE /qnas/1.json
  def destroy
    @qna.destroy
    respond_to do |format|
      format.html { redirect_to qnas_url, notice: 'Qna was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qna
      @qna = Qna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qna_params
      params.require(:qna).permit(:title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/qnas_helper.rb
module QnasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/qnas/_form.html.erb
<%= form_for(@qna) do |f| %>
  <% if @qna.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qna.errors.count, "error") %> prohibited this qna from being saved:</h2>

      <ul>
      <% @qna.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title , :class => "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => "content-area form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "작성" , :class => "btn btn-lg btn-block offset-sm-4 col-4"  %>
  </div>
<% end %>

app/views/qnas/edit.html.erb
<div class="offset-sm-3 col-6" style="margin-top: 5%;">
<h1>Editing QnA</h1>

<%= render 'form' %>

<%= link_to 'Show', @qna %> |
<%= link_to 'Back', qnas_path %>

app/views/qnas/index.html.erb
<%= link_to 'Q&A',new_qna_path, :class => "btn btn-lg btn-block offset-5", :style => "width: 17%; margin-top:10%; margin-bottom: 1%" %>

<% @qnas.each do |qna| %>
  <div class="overly offset-3"></div> 
  <a href="/qnas/<%= qna.id %>" class="review-card offset-3">
    <div class="d-flex justify-content-between">
      <b>작성 번호: <%=qna.id%></b>
      <h5><%= qna.title %></h5>
      <b>작성자: <%=qna.user.name%></b>
    </div>
    <br/>
    <div class="">
      <center><p><%= content_tag(:span, truncate( raw( sanitize(qna.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 100, :omission => "..."), class: "etc") %></p></center>
    </div>
  </a>
<%end%>
<%= paginate @qnas %>

app/views/qnas/new.html.erb
<div class="offset-sm-3 col-6" style="margin-top: 5%;">
<%= render 'form' %>

<center><%= link_to 'Back', qnas_path %></center>
</div>

app/views/qnas/show.html.erb
<div class="show-container offset-3" style="margin-top:10%">
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Title:</strong>
    <%= @qna.title %>
  </p>
  
  <p>
    <strong>Content:</strong>
    <%= @qna.content %>
  </p>
  
  <p>
    <strong>User:</strong>
    <%= @qna.user.email %>
  </p>
  
  <% if current_user.has_any_role? :admin %>
  <%= form_for(@qnacomment, url: qna_qnacomments_path(@qna), remote: true) do |f| %>
    <div class="input-field">
      <%= f.text_area :qnacomment, class: "materialize-textarea", placeholder: "댓글쓰기...", required: true, id: "qnacomment" %>
    </div>
    <div class="input-field">
      <%= f.button "댓글 쓰기", class: "btn indigo darken-4 right" %>
    </div>
  <% end %><br><br>
  <% end %>
  <% if @qna.qnacomments.present? %>
      <ul class="collection">
        <div id="qnacomment_box">
          <% @qna.qnacomments.each do |q| %>
            <li class="collection-item" id="qnacomment_<%= q.id %>">
              <span class="title"><%= @qna.user.email %></span>
              <span class="right"><%= time_ago_in_words q.created_at %></span><br><br><br>
              <span class="pre-line"><%= q.qnacomment %></span>
              <% if q.user.id == current_user.id %>
                <%= link_to '삭제', qna_qnacomment_path(@qna, q), method: :delete, class: "right", remote: true %>
              <% end %>
            </li>
          <% end %>
        </div>
      </ul>
    <% else %>
      <ul class="collection">
        <div id="qnacomment_box">
        </div>
      </ul>
    <% end %>
  
  <center><%= link_to 'Edit', edit_qna_path(@qna) %> |
  <%= link_to 'Back', qnas_path %></center>
</div>