config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :qnas do
    resources :qnacomments, only: [:create, :destroy], defaults: { format: 'js' }
  end
  resources :notices
  resources :posts do
    resources :comments, only: [:create, :destroy], defaults: { format: 'js' }
  end
  get '/posts/:membertype/search' => 'posts#search'
  root 'home#temp'
  get 'home/temp'
  get 'home/index'
  get 'home/matching'
  get '/mypages/:user_id' => "mypages#index"
  put '/mypages/:user_id/like', to: 'mypages#upvote', as: 'like_mypage'
  put '/mypages/:user_id/dislike', to: 'mypages#downvote', as: 'dislike_mypage'
  post '/posts/:post_id' =>"comments#create"
  get '/reviews/new/:post_id' => 'reviews#new'
  post '/reviews/:post_id' => 'reviews#create'
  post '/portfolios/create' => "portfolios#create"
  get '/portfolios/index'
  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/mypage/index'
  get 'portfolios/edit' => "portfolios#edit"
  post '/portfolios/update' => "portfolios#update"
  get '/matching/:post_id/:name' => "posts#matching", :constraints  => { :name => /[0-z\.]+/ }
  devise_for :users
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    # if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/matching.rb
class Matching < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/mypage.rb
class Mypage < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :portfolios
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :user
  paginates_per 5 
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :reviews
  has_many :matchings
  scope :published, -> {where.not(created_at: nil)}
  scope :unpublished, -> {where(created_at: nil)}
  paginates_per 3 
  def self.search(query)
    self.where("membertype LIKE ?","%#{query}%")
  end
end

app/models/qna.rb
class Qna < ActiveRecord::Base
  belongs_to :user
  has_many :qnacomments
  paginates_per 5
end

app/models/qnacomment.rb
class Qnacomment < ActiveRecord::Base
  belongs_to :user
  belongs_to :qna
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  paginates_per 3 
end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :assign_default_role
  rolify
  acts_as_voter
  # 프로필 사진 추가를 위해 Uploader 생성
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # validates :name, presence: true, uniqueness: true
  has_many :posts
  has_many :reviews
  has_many :comments
  has_many :qnacomments
  has_many :ratings
  # User Avatar Validation
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  # validate :password_complexity
  
  # def password_complexity
  #   return if password.blank? || password =~ /^(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,15}$/

  #   errors.add :password, '를 숫자, 특수문자를 포함하여 6자 이상으로 설정해주세요.'
  # end

  scope :supply, -> {where(user_type: "1")}
  scope :demand, -> {where(user_type: "2")}
  scope :admin, -> {where(user_type: "3")}

  def assign_default_role
    if self.user_type == "1"
      add_role(:supply)
    elsif self.user_type =="2"
      add_role(:demand)
    else
      add_role(:admin)
    end
  end
  
  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy, :search]

  def matching
    @matching = Matching.create(user_id: current_user.id, post_id: params[:post_id], supply: params[:name].to_s, status: 1)
    redirect_to :back
  end

  def search
    @test = params[:category]
    @posts = Post.where(membertype: "2", category: params[:category])
    @posts = @posts.order("created_at DESC").page params[:page]
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.search(params[:membertype])
    @posts = Post.order("created_at DESC").page params[:page]
    @temp = params[:membertype]
    @users = User.where(user_type: "1")
    @mypages = Mypage.order(:cached_votes_up => :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @matching = Matching.find_by(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.membertype = current_user.user_type

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/qnas_helper.rb
module QnasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-12">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <!-- 카테고리 -->
  <div class="radio-group">
    <%= f.radio_button :category, '리모델링' , checked: true %> 리모델링
    <%= f.radio_button :category, '공사', checked: true %> 공사
    <%= f.radio_button :category, '리모델링+공사', checked: true %> 리모델링+공사
    </div>
  <!-- tinymce 편집기 적용 -->
  <div class="form-group">
      <%= f.label :content %>
      <%= tinymce %>
      <%= f.text_area :content, id: :content, class: "content-area form-control tinymce", rows: "10" %>
  </div>
  <div class="actions">
    <%= f.submit "작성" , :class => "btn btn-lg btn-block offset-sm-4 col-4"%>
  </div>
<% end %>
  </div>
</div>

app/views/posts/index.html.erb
  <% if @temp == "1" %>
    <div class="post-body offset-2 col-8">
  		<% @mypages.each do |mypage| %>
  			<% if mypage.user.user_type == "1" %>
  			<div class="supply-card">
  				<div id="image-section-padding">
  					<% if mypage.user.avatar.blank? %>
  		         <%= link_to image_tag("default_image.png", :class => "profile-img"), "/mypages/#{mypage.user.id}"%>
  		      <% else %>
  		          <%= link_to image_tag("#{mypage.user.avatar}", :class => "profile-img"), "/mypages/#{mypage.user.id}"%>
  		      <% end %>
  				</div>
  				<div id="supply-inform">
  					<!-- 이름 -->
  						<label>이름 : </label><%= mypage.user.name %><br/>
  					<!-- 한줄 소개 -->
  						<label>한줄 소개 : </label><%= mypage.user.introduce %><br/>
  					<!-- 평점 -->
  					  <label>평점 : </label><%= mypage.user.rating %>
  				</div>
  				<div id="like-worst">
  						<label class="like-worst-label">좋아요 : <%= mypage.get_upvotes.size %></label>
              <label class="like-worst-label">싫어요 : <%= mypage.get_downvotes.size %></label>
  				</div>
  			</div>
  		<%end%>
  	<%end%>
  </div>
  <!--소비자-->
  <% elsif @temp == "2" %>
  <center style="margin-top: 7%;">
    <% if (current_user.user_type == "2" && @temp == "2") || (current_user.user_type == "3" && @temp == "2") %>
      <%= link_to '생성', new_post_path, :class => 'btn btn-lg btn-block', :style => "background-color: #96B566; width: 20%; margin-bottom: 5%" %>
    <% end %>
    <form action="/posts/2/search" method="get">
      <select class="custom-select col-2" name="category" style="font-size: 14px;">
        <option selected>분류</option>
        <option value="공사">공사</option>
        <option value="리모델링">리모델링</option>
        <option value="리모델링+공사">리모델링+공사</option>
      </select>
      <button type="submit" style="color:white; font-size:13px;" class="btn btn-lg">이동</button>
    </form>
  </center>
  <div class="container">
    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th class="text-center">번호</th>
          <th class="text-center">이름</th>
          <th class="text-center">제목</th>
          <th class="text-center">내용</th>
          <th class="text-center">분류</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td class="text-center"><%=post.id%></td>
            <td class="text-center"><%=post.user.name%></td>
            <td class="text-center"><%= link_to post.title, post, :class => "post-title-text" %></td>
            <td class="text-center"><%=post.content.html_safe%></td>
            <td class="text-center"><%=post.category%></td>
            <td class="text-center">
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
  <% end %>
  <%= paginate @posts %>

app/views/posts/new.html.erb
<div class="customer-form offset-sm-3 col-6", style="margin-top: 5%;">
    <%= render 'form' %>
    
    <center><%= link_to 'Back', posts_path %></center>
</div>

app/views/posts/search.html.erb
<br><br><br><br><br>
<center>
<% if (current_user.user_type == "2") || (current_user.user_type == "3") %>
  <%= link_to '생성', new_post_path, :class => 'btn btn-lg btn-block', :style => "background-color: #96B566; width: 20%; margin-bottom: 5%" %>
<% end %>
<form action="/posts/2/search" method="get">
  <select class="custom-select col-2" name="category" style="font-size: 14px;">
    <option selected>분류</option>
    <option value="공사">공사</option>
    <option value="리모델링">리모델링</option>
    <option value="리모델링+공사">리모델링+공사</option>
  </select>
  <button type="submit" style="color:white; font-size:13px;" class="btn btn-danger btn-sm btn-signin">이동</button>
</form>
</center>
<div class="container">
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th class="text-center">번호</th>
      <th class="text-center">이름</th>
      <th class="text-center">제목</th>
      <th class="text-center">내용</th>
      <th class="text-center">분류</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td class="text-center"><%=post.id%></td>
        <td class="text-center"><%=post.user.name%></td>
        <td class="text-center"><%= link_to post.title, post, :class => "post-title-text" %></td>
        <td class="text-center"><%=post.content.html_safe%></td>
        <td class="text-center"><%=post.category%></td>
        <td class="text-center">
          <%= link_to '수정', edit_post_path(post) , :class => "btn", :style => "background-color: #BCE27F;" %>
          <%= link_to '삭제', post, method: :delete, :class => "btn btn-light post-title-delete",  data: { confirm: '정말 삭제하시겠습니까?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
  <%= paginate @posts %>

app/views/posts/show.html.erb
<div class="show-container offset-3" style="margin-top: 10%;">
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content.html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>

<%= form_for(@comment, url: post_comments_path(@post), remote: true) do |f| %>
  <div class="input-field">
    <%= f.text_area :comment, class: "form-control", placeholder: "댓글쓰기...", required: true, id: "comment", rows: "3" %>
  </div>
  <br />
  <div class="input-field">
    <%= f.button "댓글 쓰기", class: "btn indigo darken-4 right" %>
    <% if @matching.nil? %>
    
    <% else %>
    <%= link_to "리뷰 쓰기", "/reviews/new/#{@post.id}", class: "btn indigo darken-4 right" %>
    <% end %>
  </div>
<% end %><br><br>
<script>
function matching() {
  var input = prompt("매칭", "공급자의 이메일을 입력해주세요.");
  document.getElementById("supply").value = input;
  
  var address = "/matching/" + <%= @post.id %> + "/" + input;
  
  location.replace(address);
}
</script>
<% if @post.user_id == current_user.id %>
<input type="text" name="supply" id="supply">
<button type="button" name="matching" id="matching" onclick="matching();">매칭 완료</button>
<% end %>
<% if @post.comments.present? %>
    <ul class="collection">
      <div id="comment_box">
        <% @post.comments.each do |c| %>
          <li class="collection-item" id="comment_<%= c.id %>">
            <span class="title"><%= @post.user.email %></span>
            <span class="right"><%= time_ago_in_words c.created_at %></span><br><br><br>
            <span class="pre-line"><%= c.comment %></span>
            <% if c.user.id == current_user.id %>
              <%= link_to '삭제', post_comment_path(@post, c), method: :delete, class: "right", remote: true %>
            <% end %>
          </li>
        <% end %>
      </div>
    </ul>
  <% else %>
    <ul class="collection">
      <div id="comment_box">
      </div>
    </ul>
  <% end %>

<% if @post.user == current_user %>
<%= link_to '수정', edit_post_path(@post) %> 
<%= link_to '뒤로가기', '/posts?membertype=2' %>
<%= link_to '삭제', @post, method: :delete, data: { confirm: '정말 삭제하시겠습니까?' } %>
<% end %>
</div>