config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :qnas do
    resources :qnacomments, only: [:create, :destroy], defaults: { format: 'js' }
  end
  resources :notices
  resources :posts do
    resources :comments, only: [:create, :destroy], defaults: { format: 'js' }
  end
  get '/posts/:membertype/search' => 'posts#search'
  root 'home#temp'
  get 'home/temp'
  get 'home/index'
  get 'home/matching'
  get '/mypages/:user_id' => "mypages#index"
  put '/mypages/:user_id/like', to: 'mypages#upvote', as: 'like_mypage'
  put '/mypages/:user_id/dislike', to: 'mypages#downvote', as: 'dislike_mypage'
  post '/posts/:post_id' =>"comments#create"
  get '/reviews/new/:post_id' => 'reviews#new'
  post '/reviews/:post_id' => 'reviews#create'
  post '/portfolios/create' => "portfolios#create"
  get '/portfolios/index'
  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/mypage/index'
  get 'portfolios/edit' => "portfolios#edit"
  post '/portfolios/update' => "portfolios#update"
  get '/matching/:post_id/:name' => "posts#matching", :constraints  => { :name => /[0-z\.]+/ }
  devise_for :users
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    # if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/matching.rb
class Matching < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/mypage.rb
class Mypage < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :portfolios
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :user
  paginates_per 5 
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :reviews
  has_many :matchings
  scope :published, -> {where.not(created_at: nil)}
  scope :unpublished, -> {where(created_at: nil)}
  paginates_per 3 
  def self.search(query)
    self.where("membertype LIKE ?","%#{query}%")
  end
end

app/models/qna.rb
class Qna < ActiveRecord::Base
  belongs_to :user
  has_many :qnacomments
  paginates_per 5
end

app/models/qnacomment.rb
class Qnacomment < ActiveRecord::Base
  belongs_to :user
  belongs_to :qna
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  paginates_per 3 
end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :assign_default_role
  rolify
  acts_as_voter
  # 프로필 사진 추가를 위해 Uploader 생성
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # validates :name, presence: true, uniqueness: true
  has_many :posts
  has_many :reviews
  has_many :comments
  has_many :qnacomments
  has_many :ratings
  # User Avatar Validation
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  # validate :password_complexity
  
  # def password_complexity
  #   return if password.blank? || password =~ /^(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,15}$/

  #   errors.add :password, '를 숫자, 특수문자를 포함하여 6자 이상으로 설정해주세요.'
  # end

  scope :supply, -> {where(user_type: "1")}
  scope :demand, -> {where(user_type: "2")}
  scope :admin, -> {where(user_type: "3")}

  def assign_default_role
    if self.user_type == "1"
      add_role(:supply)
    elsif self.user_type =="2"
      add_role(:demand)
    else
      add_role(:admin)
    end
  end
  
  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end
end

app/controllers/reviews_controller.rb
#class ReviewsController < InheritedResources::Base
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  
  # GET /reviews
  # GET /reviews.json
  def index
    @review = Review.all
    @review = Review.order("created_at DESC").page params[:page]
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show

  end

  # GET /reviews/new
  def new
    @review = Review.new
    @temp = params[:post_id]
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.post_id = params[:post_id]
    @review.rating = params[:rating].to_i
    @matching = Matching.find_by(post_id: params[:post_id])
    @supply = User.find_by(email: @matching.supply.to_s)
    
    if @supply.rating == 0.0
      @supply.rating = params[:rating].to_i
    else
      @supply.rating = ((@supply.rating + params[:rating].to_i) / 2).round(1)
    end
    
    @supply.save
    
    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:title, :content, :rating, :avatar)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/qnas_helper.rb
module QnasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<script>
  $( document ).ready( function() {
    $(".test1")
      .click( function() { 
        $(this).attr( 'src', '/enteredstar.png' );
        $(".test2").attr( 'src', '/blankstar.png' );
        $(".test3").attr( 'src', '/blankstar.png' );
        $(".test4").attr( 'src', '/blankstar.png' );
        $(".test5").attr( 'src', '/blankstar.png' );
        $(".rating").val("1");
      } )

      $(".test2")
      .click( function() { 
        $(this).attr( 'src', '/enteredstar.png' );
        $(".test1").attr( 'src', '/enteredstar.png' );
        $(".test3").attr( 'src', '/blankstar.png' );
        $(".test4").attr( 'src', '/blankstar.png' );
        $(".test5").attr( 'src', '/blankstar.png' );
        $(".rating").val("2");
      } )

      $(".test3")
      .click( function() { 
        $(this).attr( 'src', '/enteredstar.png' );
        $(".test1").attr( 'src', '/enteredstar.png' );
        $(".test2").attr( 'src', '/enteredstar.png' );
        $(".test4").attr( 'src', '/blankstar.png' );
        $(".test5").attr( 'src', '/blankstar.png' );
        $(".rating").val("3");
      } )
      
      $(".test4")
      .click( function() { 
        $(this).attr( 'src', '/enteredstar.png' );
        $(".test1").attr( 'src', '/enteredstar.png' );
        $(".test2").attr( 'src', '/enteredstar.png' );
        $(".test3").attr( 'src', '/enteredstar.png' );
        $(".test5").attr( 'src', '/blankstar.png' );
        $(".rating").val("4");
      } )

      $(".test5")
      .click( function() { 
        $(this).attr( 'src', '/enteredstar.png' );
        $(".test1").attr( 'src', '/enteredstar.png' );
        $(".test2").attr( 'src', '/enteredstar.png' );
        $(".test3").attr( 'src', '/enteredstar.png' );
        $(".test4").attr( 'src', '/enteredstar.png' );
        $(".rating").val("5");
      } )

  } );
</script>
<%= form_for(Review.new, url: "/reviews/#{@temp}") do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title , :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_field :content , :class => "content-area form-control"%>
  </div>
  <div class="form-group">
    <%= f.hidden_field :post_id, value: "#{@temp}" %>
  </div>
  <div class="form-group">
    <%= f.file_field :avatar %>
  </div>
  <div class="form-group"><center>
    <img src="/blankstar.png" class="test1">
    <img src="/blankstar.png" class="test2">
    <img src="/blankstar.png" class="test3">
    <img src="/blankstar.png" class="test4">
    <img src="/blankstar.png" class="test5">
    <%= f.hidden_field :rating, :class => "rating", :name => "rating" %></center>
    <br>
  </div>
  <div class="actions">
    <%= f.submit "작성" , :class => "btn btn-lg btn-block offset-sm-4 col-4" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="offset-sm-3 col-6" style="margin-top: 5%;">
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<br/><br/><br/>
  <% @review.each do |review| %>
    <a href="/reviews/<%= review.id %>" class="review-card offset-3">
      <div class="d-flex justify-content-between">
        <b>작성 번호: <%=review.id%></b>
        <h5><%= review.title %></h5>
        <b>작성자: <%=review.user.name%></b>
      </div>
      <br/>
      <div class="">
        <center><p><%= content_tag(:span, truncate( raw( sanitize(review.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 100, :omission => "..."), class: "etc") %></p></center>
      </div>
  
      <div>
        <center><%= image_tag review.avatar, :style => "width: 250px; height: 250px;", :id => "image"%></center>
      </div>
      <br/>
      <div>
        <center><label>평점 : </label>
        <span><%=review.rating%></span></center>
      </div>
    </a>
  <%end%>
  <center><%= paginate @review %></center>
  <div class="container pagination justify-content-center" >
    
  </div>

app/views/reviews/new.html.erb
<div class="offset-sm-3 col-6" style="margin-top: 5%;">
<%= render 'form' %>
<center><%= link_to 'Back', reviews_path %></center>
</div>

app/views/reviews/show.html.erb
<div class="show-container offset-3" style="margin-top:10%">
<p id="notice"><%= notice %></p>

<p>
  <strong>작성자:</strong>
  <%= @review.user.name %>
</p>
<p>
  <strong>제목:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>내용:</strong>
  <%= @review.content %>
</p>
<p>
<%=image_tag(@review.avatar)%>
</p>
<center><%= link_to '수정', edit_review_path(@review), :class => "btn btn-lg col-2" %> 
<%= link_to '뒤로가기', reviews_path ,:class => "btn btn-lg col-2"%></center>

</div>